export const HolderInfo = [
    { head: 'User ID', des: 'Name here' },
    { head: 'Card Number', des: 'N555981******0406ame' },
    { head: 'Card Program', des: 'Gift Dynabook' },
    { head: 'Card Ref. Number', des: '734000407' },
    { head: 'Card Expiry Date', des: '05/24' },
    { head: 'Card Created On', des: '16/07/2021' },
    { head: 'Card Created On', des: 'GTDYNANEW1707' },
    { head: 'First Name', des: 'Last Name' },
    { head: 'Last Name', des: 'Last Name' },
    { head: 'Date of Birth', des: 'Date of Birth' },
    { head: 'Address 1', des: '01 Ravoos Chaitra 2nd Cross' },
    { head: 'Address 2', des: '01 Ravoos Chaitra 2nd Cross' },
    { head: 'City', des: 'Bangalore' },
    { head: 'State/Province', des: 'Karnataka' },
    { head: 'Zip/Postal Code', des: '560037' },
    { head: 'Country', des: 'India' },
    { head: 'Card Status', des: 'Here Secret Question' },
    { head: 'Balance', des: '$ 45' },
    { head: 'Mobile Number', des: '9742293421' },
    { head: 'E-mail', des: 'rajasreddy.ys@gmail.com' },
]